-- Seed 50 starter brands across all four price tiers.
-- Distribution: 10 budget / 15 mid / 15 premium / 10 luxury.
-- is_shopify=true means we believe the brand runs on Shopify and
--   /products.json is accessible; set false when uncertain.
-- Run /admin/brands → "Bulk Verify" after applying to confirm live endpoints.
-- Shopify collection slugs are empty by default — populated via the admin
-- verification tool as we confirm which slugs actually return products.

INSERT INTO public.curated_brands
  (name, slug, domain, shopify_base_url, shopify_collection_slugs, is_shopify,
   price_tier, typical_price_min, typical_price_max,
   aesthetic_tags, cultural_signals, typical_colors, typical_fits,
   gender_focus, geo_region, notes)
VALUES

-- ════════════════════════════════════════════════════════════════════════════
-- BUDGET ($20–$90)
-- ════════════════════════════════════════════════════════════════════════════

('True Classic', 'true-classic', 'trueclassic.com',
 'https://trueclassic.com', '{}', TRUE,
 'budget', 20, 60,
 ARRAY['basics','minimalist','everyday'],
 ARRAY['everyday','casual'],
 ARRAY['black','white','navy','gray','olive'],
 ARRAY['relaxed','slim'],
 'mens', 'US', 'Premium-fit basics DTC; Shopify'),

('Fresh Clean Threads', 'fresh-clean-threads', 'freshcleanthreads.com',
 'https://freshcleanthreads.com', '{}', TRUE,
 'budget', 25, 55,
 ARRAY['basics','minimalist'],
 ARRAY['everyday','casual'],
 ARRAY['black','white','navy','heather-gray'],
 ARRAY['slim','relaxed'],
 'mens', 'US', 'Basics DTC; Shopify'),

('Cuts Clothing', 'cuts-clothing', 'cuts.com',
 'https://cuts.com', '{}', TRUE,
 'budget', 38, 88,
 ARRAY['basics','performance','smart-casual'],
 ARRAY['work-casual','everyday'],
 ARRAY['black','white','navy','slate','olive'],
 ARRAY['slim','tailored'],
 'mens', 'US', 'Performance-fit basics; Shopify'),

('Entireworld', 'entireworld', 'theentireworld.com',
 'https://theentireworld.com', '{}', TRUE,
 'budget', 45, 98,
 ARRAY['basics','sustainable','minimalist'],
 ARRAY['everyday','eco'],
 ARRAY['natural','cream','gray','navy'],
 ARRAY['relaxed','oversized'],
 'all', 'US', 'Sustainable basics; Shopify'),

('American Giant', 'american-giant', 'american-giant.com',
 'https://www.american-giant.com', '{}', TRUE,
 'budget', 40, 120,
 ARRAY['americana','basics','quality-basics'],
 ARRAY['american-made','everyday'],
 ARRAY['black','navy','gray','heather'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'Made-in-USA basics; Shopify'),

('Outerknown', 'outerknown', 'outerknown.com',
 'https://www.outerknown.com', '{}', TRUE,
 'budget', 45, 135,
 ARRAY['coastal','sustainable','surf-casual'],
 ARRAY['surf','eco','outdoor'],
 ARRAY['natural','earth-tones','navy','sage'],
 ARRAY['relaxed','loose'],
 'all', 'US', 'Sustainable surf casual; Shopify'),

('Vuori', 'vuori', 'vuori.com',
 'https://vuori.com', '{}', TRUE,
 'budget', 55, 115,
 ARRAY['athleisure','performance','coastal'],
 ARRAY['yoga','outdoor','active'],
 ARRAY['navy','gray','olive','black'],
 ARRAY['relaxed','slim'],
 'all', 'US', 'Premium activewear casual; Shopify'),

('Public Rec', 'public-rec', 'publicrec.com',
 'https://www.publicrec.com', '{}', TRUE,
 'budget', 65, 115,
 ARRAY['smart-casual','performance','basics'],
 ARRAY['work-casual','travel'],
 ARRAY['black','navy','charcoal','olive'],
 ARRAY['slim','tailored'],
 'mens', 'US', 'All-day comfort wear; Shopify'),

('Huckberry', 'huckberry', 'huckberry.com',
 'https://huckberry.com', '{}', TRUE,
 'budget', 35, 150,
 ARRAY['outdoor-casual','americana','rugged-casual'],
 ARRAY['outdoor','adventure','heritage'],
 ARRAY['earth-tones','olive','navy','flannel'],
 ARRAY['relaxed','classic'],
 'mens', 'US', 'Outdoor lifestyle retailer; Shopify (multi-brand)'),

('Taylor Stitch', 'taylor-stitch', 'taylorstitch.com',
 'https://www.taylorstitch.com', '{}', TRUE,
 'budget', 55, 175,
 ARRAY['americana','rugged-casual','heritage'],
 ARRAY['outdoor','workwear','classic'],
 ARRAY['earth-tones','indigo','olive','brown'],
 ARRAY['relaxed','classic'],
 'mens', 'US', 'Crowdfunded quality menswear; Shopify'),

-- ════════════════════════════════════════════════════════════════════════════
-- MID ($50–$250)
-- ════════════════════════════════════════════════════════════════════════════

('Stüssy', 'stussy', 'stussy.com',
 'https://www.stussy.com', '{}', TRUE,
 'mid', 50, 200,
 ARRAY['streetwear','surf','skate','graphic'],
 ARRAY['skate','surf','hip-hop','LA'],
 ARRAY['black','white','navy','natural'],
 ARRAY['relaxed','oversized'],
 'all', 'US', 'OG streetwear brand; Shopify'),

('Carhartt WIP', 'carhartt-wip', 'carhartt-wip.com',
 'https://www.carhartt-wip.com', '{}', TRUE,
 'mid', 60, 250,
 ARRAY['streetwear','workwear','utility'],
 ARRAY['skate','hip-hop','workwear'],
 ARRAY['black','brown','navy','stone'],
 ARRAY['relaxed','loose'],
 'all', 'US', 'Workwear-inspired streetwear; Shopify'),

('Saturdays NYC', 'saturdays-nyc', 'saturdaysnyc.com',
 'https://www.saturdaysnyc.com', '{}', TRUE,
 'mid', 65, 250,
 ARRAY['surf-casual','coastal','smart-casual'],
 ARRAY['surf','NYC','weekend'],
 ARRAY['navy','white','natural','earth-tones'],
 ARRAY['relaxed','classic'],
 'mens', 'US', 'NYC surf-casual lifestyle; Shopify'),

('Buck Mason', 'buck-mason', 'buckmason.com',
 'https://buckmason.com', '{}', TRUE,
 'mid', 55, 165,
 ARRAY['basics','americana','smart-casual'],
 ARRAY['California','heritage','everyday'],
 ARRAY['black','white','navy','indigo','stone'],
 ARRAY['slim','classic'],
 'mens', 'US', 'Quality American basics; Shopify'),

('Alex Mill', 'alex-mill', 'alexmill.com',
 'https://alexmill.com', '{}', TRUE,
 'mid', 65, 195,
 ARRAY['smart-casual','NY-casual','basics'],
 ARRAY['NYC','weekend','classic'],
 ARRAY['navy','white','natural','stripe'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'NYC casual basics; Shopify'),

('Reigning Champ', 'reigning-champ', 'reigningchamp.com',
 'https://www.reigningchamp.com', '{}', TRUE,
 'mid', 75, 225,
 ARRAY['premium-basics','athletic','minimalist'],
 ARRAY['gym','athletic','quality'],
 ARRAY['black','charcoal','navy','gray'],
 ARRAY['slim','fitted'],
 'all', 'US', 'Premium athletic basics; Shopify'),

('Todd Snyder', 'todd-snyder', 'toddsnyder.com',
 'https://www.toddsnyder.com', '{}', TRUE,
 'mid', 95, 350,
 ARRAY['smart-casual','preppy','americana','menswear'],
 ARRAY['NYC','menswear','classic'],
 ARRAY['navy','olive','tan','black','white'],
 ARRAY['slim','tailored','classic'],
 'mens', 'US', 'NYC menswear; Shopify confirmed working'),

('John Elliott', 'john-elliott', 'johnelliott.co',
 'https://johnelliott.co', '{}', TRUE,
 'mid', 95, 350,
 ARRAY['LA-casual','minimalist','luxury-streetwear'],
 ARRAY['LA','luxury-streetwear'],
 ARRAY['black','white','navy','slate'],
 ARRAY['relaxed','slim'],
 'mens', 'US', 'LA minimalist premium basics; Shopify'),

('Human Made', 'human-made', 'humanmade.jp',
 'https://humanmade.jp', '{}', TRUE,
 'mid', 90, 400,
 ARRAY['streetwear','graphic','Japanese','vintage'],
 ARRAY['hip-hop','Japanese-street','vintage'],
 ARRAY['natural','black','white','indigo'],
 ARRAY['relaxed','classic'],
 'all', 'JP', 'NIGO Japanese streetwear; Shopify'),

('Aritzia', 'aritzia', 'aritzia.com',
 'https://www.aritzia.com', '{}', TRUE,
 'mid', 55, 200,
 ARRAY['smart-casual','elevated-basics','contemporary'],
 ARRAY['work-casual','weekend','polished'],
 ARRAY['black','white','cream','camel','navy'],
 ARRAY['slim','tailored','fitted'],
 'womens', 'US', 'Canadian womens contemporary; Shopify'),

('Faherty Brand', 'faherty-brand', 'fahertybrand.com',
 'https://fahertybrand.com', '{}', TRUE,
 'mid', 60, 200,
 ARRAY['coastal','surf-casual','americana'],
 ARRAY['surf','beach','California'],
 ARRAY['earth-tones','natural','navy','coral'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'American coastal casual; Shopify'),

('Wax London', 'wax-london', 'waxlondon.com',
 'https://www.waxlondon.com', '{}', TRUE,
 'mid', 75, 210,
 ARRAY['British-casual','smart-casual','minimal'],
 ARRAY['London','weekend','casual-chic'],
 ARRAY['earth-tones','olive','natural','brown'],
 ARRAY['relaxed','classic'],
 'mens', 'GB', 'London smart casual; Shopify'),

('Rowing Blazers', 'rowing-blazers', 'rowingblazers.com',
 'https://rowingblazers.com', '{}', TRUE,
 'mid', 100, 400,
 ARRAY['preppy','ivy-league','sport','heritage'],
 ARRAY['prep','collegiate','sport','humor'],
 ARRAY['navy','red','white','green','stripe'],
 ARRAY['classic','relaxed'],
 'all', 'US', 'Preppy sport revival; Shopify'),

('Percival', 'percival', 'percivalclo.com',
 'https://www.percivalclo.com', '{}', TRUE,
 'mid', 75, 210,
 ARRAY['British-casual','smart-casual','graphic'],
 ARRAY['London','weekend','creative'],
 ARRAY['earth-tones','cream','navy','olive'],
 ARRAY['relaxed','slim'],
 'mens', 'GB', 'London contemporary casual; Shopify'),

('Onia', 'onia', 'onia.com',
 'https://www.onia.com', '{}', TRUE,
 'mid', 75, 200,
 ARRAY['coastal','resort','smart-casual'],
 ARRAY['beach','resort','Hamptons'],
 ARRAY['white','navy','earth-tones','blue'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'Resort-coastal lifestyle brand; Shopify'),

-- ════════════════════════════════════════════════════════════════════════════
-- PREMIUM ($120–$600)
-- ════════════════════════════════════════════════════════════════════════════

('Aimé Leon Dore', 'aime-leon-dore', 'aimeleondore.com',
 'https://www.aimeleondore.com', '{}', TRUE,
 'premium', 120, 600,
 ARRAY['preppy','streetwear','NY','luxury-streetwear','vintage'],
 ARRAY['NYC','basketball','prep','hip-hop'],
 ARRAY['earth-tones','tan','navy','brown','cream'],
 ARRAY['relaxed','classic'],
 'mens', 'US', 'NY preppy streetwear; Shopify'),

('Norse Projects', 'norse-projects', 'norseprojects.com',
 'https://norseprojects.com', '{}', TRUE,
 'premium', 120, 450,
 ARRAY['Scandinavian','minimalist','functional'],
 ARRAY['Copenhagen','outdoor','minimal'],
 ARRAY['navy','earth-tones','gray','natural','olive'],
 ARRAY['relaxed','classic'],
 'all', 'EU', 'Copenhagen minimalist; Shopify'),

('Our Legacy', 'our-legacy', 'ourlegacy.cc',
 'https://www.ourlegacy.cc', '{}', TRUE,
 'premium', 150, 550,
 ARRAY['Scandinavian','experimental','avant-garde','minimal'],
 ARRAY['Stockholm','art','music'],
 ARRAY['black','earth-tones','white','natural'],
 ARRAY['relaxed','oversized'],
 'all', 'EU', 'Stockholm experimental minimal; Shopify'),

('A.P.C.', 'apc', 'apcus.com',
 'https://www.apcus.com', '{}', TRUE,
 'premium', 150, 500,
 ARRAY['French-minimal','smart-casual','classic'],
 ARRAY['Paris','understated','classic'],
 ARRAY['navy','black','ecru','indigo','stone'],
 ARRAY['slim','tailored'],
 'all', 'US', 'French minimal; Shopify US store'),

('Corridor NYC', 'corridor-nyc', 'corridornyc.com',
 'https://corridornyc.com', '{}', TRUE,
 'premium', 150, 400,
 ARRAY['NY-menswear','smart-casual','heritage'],
 ARRAY['NYC','weekend','classic'],
 ARRAY['earth-tones','navy','natural'],
 ARRAY['relaxed','classic'],
 'mens', 'US', 'NYC menswear essentials; Shopify'),

('Wood Wood', 'wood-wood', 'woodwood.com',
 'https://www.woodwood.com', '{}', TRUE,
 'premium', 100, 400,
 ARRAY['Scandinavian-streetwear','minimal','graphic'],
 ARRAY['Copenhagen','streetwear','design'],
 ARRAY['black','white','earth-tones','navy'],
 ARRAY['relaxed','oversized'],
 'all', 'EU', 'Copenhagen streetwear/minimal; Shopify'),

('Drake''s', 'drakes', 'drakes.com',
 'https://drakes.com', '{}', TRUE,
 'premium', 150, 650,
 ARRAY['British-heritage','menswear','classic','smart-casual'],
 ARRAY['London','heritage','tailoring'],
 ARRAY['earth-tones','navy','brown','tan','cream'],
 ARRAY['tailored','classic'],
 'mens', 'GB', 'British heritage menswear; Shopify'),

('Knickerbocker', 'knickerbocker', 'knickerbockermfg.com',
 'https://www.knickerbockermfg.com', '{}', TRUE,
 'premium', 100, 400,
 ARRAY['workwear-heritage','americana','NY'],
 ARRAY['NYC','heritage','workwear'],
 ARRAY['indigo','natural','earth-tones','black'],
 ARRAY['relaxed','classic'],
 'mens', 'US', 'NYC heritage workwear; Shopify'),

('Denim Tears', 'denim-tears', 'denimtears.com',
 'https://denimtears.com', '{}', TRUE,
 'premium', 150, 500,
 ARRAY['streetwear','cultural','graphic','americana'],
 ARRAY['Black-culture','hip-hop','art'],
 ARRAY['black','white','indigo','natural'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'Tremaine Emory cultural streetwear; Shopify'),

('Jacquemus', 'jacquemus', 'jacquemus.com',
 'https://www.jacquemus.com', '{}', TRUE,
 'premium', 150, 800,
 ARRAY['French-contemporary','minimalist','avant-garde'],
 ARRAY['Paris','art','fashion'],
 ARRAY['earth-tones','white','natural','terracotta'],
 ARRAY['oversized','fitted'],
 'all', 'EU', 'French contemporary fashion; Shopify'),

('Ami Paris', 'ami-paris', 'us.amiparis.com',
 'https://us.amiparis.com', '{}', TRUE,
 'premium', 150, 600,
 ARRAY['French-preppy','smart-casual','Parisian'],
 ARRAY['Paris','classic','everyday-luxury'],
 ARRAY['black','navy','white','red'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'Parisian everyday luxury; Shopify US store'),

('Sandro', 'sandro', 'us.sandro-paris.com',
 'https://us.sandro-paris.com', '{}', TRUE,
 'premium', 150, 600,
 ARRAY['French-contemporary','smart-casual','Parisian'],
 ARRAY['Paris','office-casual','weekend'],
 ARRAY['black','white','navy','earth-tones'],
 ARRAY['slim','tailored'],
 'all', 'US', 'French contemporary; Shopify US store'),

('Staud', 'staud', 'staud.clothing',
 'https://staud.clothing', '{}', TRUE,
 'premium', 100, 450,
 ARRAY['contemporary','elevated-casual'],
 ARRAY['LA','weekend','elevated'],
 ARRAY['earth-tones','natural','cream','rust'],
 ARRAY['relaxed','fitted'],
 'womens', 'US', 'LA contemporary womens; Shopify'),

('The Frankie Shop', 'the-frankie-shop', 'thefrankieshop.com',
 'https://www.thefrankieshop.com', '{}', TRUE,
 'premium', 100, 500,
 ARRAY['contemporary','minimalist','oversized'],
 ARRAY['fashion-forward','minimal','NYC'],
 ARRAY['black','camel','cream','gray'],
 ARRAY['oversized','relaxed'],
 'womens', 'US', 'Contemporary oversized minimalism; Shopify'),

('Sporty & Rich', 'sporty-and-rich', 'sportyandrich.com',
 'https://www.sportyandrich.com', '{}', TRUE,
 'premium', 95, 400,
 ARRAY['athleisure','vintage-sporty','luxury-sportswear','preppy'],
 ARRAY['tennis','vintage-athletic','wellness'],
 ARRAY['cream','white','pink','navy','green'],
 ARRAY['relaxed','oversized'],
 'all', 'US', 'Luxury vintage sporty aesthetic; Shopify'),

-- ════════════════════════════════════════════════════════════════════════════
-- LUXURY ($300+)
-- ════════════════════════════════════════════════════════════════════════════

('Acne Studios', 'acne-studios', 'acnestudios.com',
 'https://www.acnestudios.com', '{}', TRUE,
 'luxury', 200, 1500,
 ARRAY['Scandinavian-luxury','minimal','avant-garde'],
 ARRAY['Stockholm','art','fashion','intellectual'],
 ARRAY['black','white','earth-tones'],
 ARRAY['oversized','relaxed'],
 'all', 'EU', 'Stockholm luxury minimal; Shopify'),

('Bode', 'bode', 'bodenewyork.com',
 'https://bodenewyork.com', '{}', TRUE,
 'luxury', 400, 3000,
 ARRAY['heritage','vintage','artisanal','americana'],
 ARRAY['craft','antique-textiles','americana','art'],
 ARRAY['natural','patchwork','earth-tones'],
 ARRAY['relaxed','classic'],
 'all', 'US', 'NYC artisanal heritage; Shopify'),

('Khaite', 'khaite', 'khaite.com',
 'https://www.khaite.com', '{}', TRUE,
 'luxury', 400, 3000,
 ARRAY['NY-luxury','minimalist','quiet-luxury'],
 ARRAY['NYC','fashion','elevated'],
 ARRAY['black','cream','camel','navy'],
 ARRAY['tailored','fitted','relaxed'],
 'womens', 'US', 'NY quiet luxury; Shopify'),

('Nanushka', 'nanushka', 'nanushka.com',
 'https://www.nanushka.com', '{}', TRUE,
 'luxury', 250, 1500,
 ARRAY['sustainable-luxury','Scandinavian','minimal','vegan'],
 ARRAY['fashion','sustainable','art'],
 ARRAY['earth-tones','black','cream','rust'],
 ARRAY['relaxed','oversized'],
 'all', 'EU', 'Budapest sustainable luxury; Shopify'),

('By Malene Birger', 'by-malene-birger', 'bymalenebirger.com',
 'https://www.bymalenebirger.com', '{}', TRUE,
 'luxury', 200, 1000,
 ARRAY['Scandinavian-luxury','feminine','contemporary'],
 ARRAY['Copenhagen','fashion','sophisticated'],
 ARRAY['black','cream','earthy','print-heavy'],
 ARRAY['fitted','relaxed'],
 'womens', 'EU', 'Danish luxury contemporary; Shopify'),

('Wales Bonner', 'wales-bonner', 'walesbonner.net',
 'https://www.walesbonner.net', '{}', TRUE,
 'luxury', 300, 2000,
 ARRAY['luxury','cultural','heritage','Afro-Atlantic'],
 ARRAY['art','music','heritage','fashion'],
 ARRAY['earth-tones','cream','brown','black'],
 ARRAY['tailored','relaxed'],
 'all', 'GB', 'Afro-Atlantic heritage luxury; Shopify'),

('Lemaire', 'lemaire', 'lemaire.fr',
 'https://www.lemaire.fr', '{}', FALSE,
 'luxury', 400, 2000,
 ARRAY['French-luxury','minimalist','utilitarian'],
 ARRAY['Paris','art','fashion','intellectual'],
 ARRAY['earth-tones','stone','cream','black'],
 ARRAY['relaxed','oversized'],
 'all', 'EU', 'French minimalist luxury; Shopify status unconfirmed'),

('The Row', 'the-row', 'therow.com',
 'https://www.therow.com', '{}', FALSE,
 'luxury', 800, 5000,
 ARRAY['quiet-luxury','minimalist','NY-luxury'],
 ARRAY['fashion','elevated','stealth-wealth'],
 ARRAY['cream','black','ivory','camel','stone'],
 ARRAY['relaxed','tailored'],
 'all', 'US', 'Quiet luxury pinnacle; Shopify status unconfirmed'),

('Comme des Garçons Play', 'comme-des-garcons-play', 'play.comme-des-garcons.com',
 'https://play.comme-des-garcons.com', '{}', FALSE,
 'luxury', 200, 600,
 ARRAY['Japanese-fashion','graphic','avant-garde','preppy'],
 ARRAY['art','fashion','Japanese-luxury'],
 ARRAY['black','white','navy','red'],
 ARRAY['classic','slim'],
 'all', 'JP', 'CDG Play line; Shopify status unconfirmed'),

('Maison Margiela', 'maison-margiela', 'maisonmargiela.com',
 'https://www.maisonmargiela.com', '{}', FALSE,
 'luxury', 500, 4000,
 ARRAY['avant-garde','deconstructed','conceptual'],
 ARRAY['art','fashion','intellectual','subversive'],
 ARRAY['black','white','cream'],
 ARRAY['oversized','deconstructed'],
 'all', 'EU', 'Avant-garde luxury; likely custom platform, not Shopify'),

('Casablanca', 'casablanca', 'casablancaparis.com',
 'https://www.casablancaparis.com', '{}', TRUE,
 'luxury', 350, 1500,
 ARRAY['luxury-streetwear','resort','graphic','French'],
 ARRAY['tennis','resort','luxury-sport'],
 ARRAY['white','cream','bright-patterns','earth-tones'],
 ARRAY['relaxed','oversized'],
 'all', 'EU', 'French luxury sport/resort brand; Shopify');
